#osx_image: xcode7.3
#language: generic
#matrix:
#  include:
#    - os: osx   # Xcode current toolchain build
#      env: TYPE=xcode
#    - os: osx   # SPM on OSX
#      env: TYPE=spm
#    - os: linux # SPM on Linux
#      dist: trusty
#      sudo: required
#      env: TYPE=spm
#install: if [[ "$TYPE" == "spm" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"; fi
#script: ./scripts/test $TYPE


language: objective-c
osx_image: xcode7.3
xcode_project: JSON.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: "JSON(iOS)"
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=JSON
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
skip_cleanup: true
on:
  repo: vdka/json
  tags: true
script:
  - ./scripts/test xcode
